server:
  port: 9192

spring:
  datasource:
    username: springstudent
    password: springstudent
    url: jdbc:mysql://localhost:3306/ceylon_hotel_db
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB



